"""V3 measurement primitives."""

from .bundle import MeasurementBundle
from .executable_presets import (
    ExecutableMeasurementPreset,
    build_executable_measurement_from_spec,
    build_executable_measurement_preset,
    executable_measurement_preset_names,
)
from .operators import (
    AnalysisOperator,
    BarPlotVisualizationOperator,
    BlockingDiagnosticsAnalysisOperator,
    HeatmapVisualizationOperator,
    JsonReportOperator,
    LearningCurveBasicAnalysisOperator,
    LinePlotVisualizationOperator,
    MarkdownReportOperator,
    MultiLinePlotVisualizationOperator,
    PdfReportOperator,
    PolicyDiagnosticsAnalysisOperator,
    PredictionErrorDiagnosticsAnalysisOperator,
    ReportOperator,
    VisualizationOperator,
)
from .output import AnalysisOutput, MeasurementStepResult, VisualizationOutput
from .presets import (
    MEASUREMENT_PRESET_ALIASES,
    MEASUREMENT_PRESET_FAMILIES,
    MEASUREMENT_PRESETS,
    PRESET_VERSION,
    expand_measurement_preset,
    measurement_preset_aliases,
    measurement_preset_families,
    measurement_preset_hash,
    measurement_preset_names,
    measurement_preset_payload,
    measurement_preset_registry,
)
from .registry import (
    COMPATIBILITY_MATRIX,
    MEASUREMENT_REGISTRY_VERSION,
    SLOT_REGISTRIES,
    compatibility_matrix,
    measurement_registry_hash,
    measurement_registry_payload,
    slot_registries,
)
from .spec import MeasurementSpec
from .validation import MeasurementSpecValidationError, validate_measurement_spec

__all__ = [
    "AnalysisOperator",
    "VisualizationOperator",
    "ReportOperator",
    "MeasurementBundle",
    "ExecutableMeasurementPreset",
    "build_executable_measurement_preset",
    "build_executable_measurement_from_spec",
    "executable_measurement_preset_names",
    "LearningCurveBasicAnalysisOperator",
    "PredictionErrorDiagnosticsAnalysisOperator",
    "PolicyDiagnosticsAnalysisOperator",
    "BlockingDiagnosticsAnalysisOperator",
    "LinePlotVisualizationOperator",
    "MultiLinePlotVisualizationOperator",
    "BarPlotVisualizationOperator",
    "HeatmapVisualizationOperator",
    "MarkdownReportOperator",
    "JsonReportOperator",
    "PdfReportOperator",
    "AnalysisOutput",
    "VisualizationOutput",
    "MeasurementStepResult",
    "MeasurementSpec",
    "MeasurementSpecValidationError",
    "validate_measurement_spec",
    "MEASUREMENT_REGISTRY_VERSION",
    "SLOT_REGISTRIES",
    "COMPATIBILITY_MATRIX",
    "slot_registries",
    "compatibility_matrix",
    "measurement_registry_payload",
    "measurement_registry_hash",
    "PRESET_VERSION",
    "MEASUREMENT_PRESETS",
    "MEASUREMENT_PRESET_ALIASES",
    "MEASUREMENT_PRESET_FAMILIES",
    "measurement_preset_names",
    "measurement_preset_aliases",
    "measurement_preset_registry",
    "measurement_preset_families",
    "expand_measurement_preset",
    "measurement_preset_payload",
    "measurement_preset_hash",
]
