"""V3 protocol primitives."""

from .adapters import grammar_to_runtime_protocol_config, runtime_to_grammar_protocol_spec
from .bundle import ProtocolBundle
from .instantiate import (
    PROTO_INSTANTIATION_FAILURES,
    ProtocolInstantiationArtifact,
    ProtocolInstantiationError,
    ProtocolOperatorHandle,
    instantiate_protocol_contracts,
    instantiate_protocol_from_boundary,
)
from .operators import (
    ActionConditionedConsequenceOperator,
    AdvanceOperator,
    CriterionStopOperator,
    ClassicalNoActionConsequenceOperator,
    ConsequenceOperator,
    EventAdvanceOperator,
    EmissionOperator,
    FixedEmissionOperator,
    HorizonStopOperator,
    ScheduledEmissionOperator,
    StopOperator,
    TrialAdvanceOperator,
    TrialCountStopOperator,
)
from .output import (
    AdvanceOutput,
    ConsequenceOutput,
    EmissionOutput,
    ProtocolStepResult,
    StopOutput,
)
from .presets import (
    PRESET_VERSION,
    PROTOCOL_PRESET_ALIASES,
    PROTOCOL_PRESET_FAMILIES,
    PROTOCOL_PRESETS,
    expand_protocol_preset,
    protocol_preset_aliases,
    protocol_preset_families,
    protocol_preset_hash,
    protocol_preset_names,
    protocol_preset_payload,
    protocol_preset_registry,
)
from .registry import (
    COMPATIBILITY_MATRIX,
    PROTOCOL_REGISTRY_VERSION,
    SLOT_REGISTRIES,
    compatibility_matrix,
    protocol_registry_hash,
    protocol_registry_payload,
    slot_registries,
)
from .spec import ProtocolSpec
from .validation import ProtocolSpecValidationError, validate_protocol_spec

__all__ = [
    "grammar_to_runtime_protocol_config",
    "runtime_to_grammar_protocol_spec",
    "ProtocolBundle",
    "EmissionOperator",
    "ConsequenceOperator",
    "AdvanceOperator",
    "StopOperator",
    "TrialAdvanceOperator",
    "EventAdvanceOperator",
    "TrialCountStopOperator",
    "HorizonStopOperator",
    "CriterionStopOperator",
    "FixedEmissionOperator",
    "ScheduledEmissionOperator",
    "ActionConditionedConsequenceOperator",
    "ClassicalNoActionConsequenceOperator",
    "EmissionOutput",
    "ConsequenceOutput",
    "AdvanceOutput",
    "StopOutput",
    "ProtocolStepResult",
    "ProtocolOperatorHandle",
    "ProtocolInstantiationArtifact",
    "ProtocolInstantiationError",
    "PROTO_INSTANTIATION_FAILURES",
    "instantiate_protocol_contracts",
    "instantiate_protocol_from_boundary",
    "ProtocolSpec",
    "ProtocolSpecValidationError",
    "validate_protocol_spec",
    "PROTOCOL_REGISTRY_VERSION",
    "SLOT_REGISTRIES",
    "COMPATIBILITY_MATRIX",
    "slot_registries",
    "compatibility_matrix",
    "protocol_registry_payload",
    "protocol_registry_hash",
    "PRESET_VERSION",
    "PROTOCOL_PRESETS",
    "PROTOCOL_PRESET_ALIASES",
    "PROTOCOL_PRESET_FAMILIES",
    "protocol_preset_names",
    "protocol_preset_aliases",
    "protocol_preset_registry",
    "protocol_preset_families",
    "expand_protocol_preset",
    "protocol_preset_payload",
    "protocol_preset_hash",
]
