"""V3 package surface (incremental)."""

from .agent import (
    ActionSpace,
    COMPATIBILITY_MATRIX,
    LearnerSpec,
    LearnerSpecValidationError,
    NullActionSpace,
    NullPolicy,
    SLOT_REGISTRIES,
    SingletonActionSpace,
    compatibility_matrix,
    learner_registry_hash,
    learner_registry_payload,
    slot_registries,
    validate_learner_spec,
)
from .environment import (
    CompiledProgramTestEnvironment,
    EnvironmentReset,
    EnvironmentStep,
    EnvironmentTermination,
    IEnvironment,
    RolloutHarness,
    TrialState,
)
from .operator import (
    LookaheadContract,
    NORMATIVE_STAGE_LOOKAHEAD,
    NORMATIVE_STAGE_CONTRACTS,
    NORMATIVE_STAGE_ORDER,
    PIPELINE_BASE_FIELDS,
    OperatorPipeline,
    OperatorStage,
    default_operator_pipeline,
)

__all__ = [
    "LearnerSpec",
    "LearnerSpecValidationError",
    "validate_learner_spec",
    "SLOT_REGISTRIES",
    "COMPATIBILITY_MATRIX",
    "slot_registries",
    "compatibility_matrix",
    "learner_registry_payload",
    "learner_registry_hash",
    "ActionSpace",
    "NullActionSpace",
    "SingletonActionSpace",
    "NullPolicy",
    "OperatorStage",
    "OperatorPipeline",
    "LookaheadContract",
    "NORMATIVE_STAGE_LOOKAHEAD",
    "NORMATIVE_STAGE_CONTRACTS",
    "NORMATIVE_STAGE_ORDER",
    "PIPELINE_BASE_FIELDS",
    "default_operator_pipeline",
    "IEnvironment",
    "TrialState",
    "EnvironmentReset",
    "EnvironmentTermination",
    "EnvironmentStep",
    "CompiledProgramTestEnvironment",
    "RolloutHarness",
]

