window.VSLReact = window.VSLReact || {};

function preset(def) {
  return {
    mechanisms: [],
    phaseSummary: "",
    teaches: "",
    builderNext: "",
    nextPhenomenon: "",
    builderHref: "/ui/builder.html",
    ...def,
  };
}

window.VSLReact.presetSections = [
  {
    title: "Baseline Foundations",
    note: "Start here to learn core phase behavior before mechanism tuning.",
    items: [
      preset({
        name: "Acquisition",
        description: "Phase: Acquisition.",
        phaseSummary: "Acquisition",
        teaches: "How associative strength grows under repeated reinforced CS trials.",
        builderNext: "Change alpha, outcome, or CS identity and compare learning curves.",
        nextPhenomenon: "Extinction",
        href: "/ui/presets/acquisition.html",
      }),
      preset({
        name: "Extinction",
        description: "Phases: Acquisition -> Nonreinforcement.",
        phaseSummary: "Acquisition -> Nonreinforcement",
        teaches: "How learned responding decays when reinforcement is withheld.",
        builderNext: "Add a probe phase to inspect residual responding after extinction.",
        nextPhenomenon: "Differential Acquisition",
        href: "/ui/presets/extinction.html",
      }),
      preset({
        name: "Compound Acquisition",
        description: "Phase: Compound Acquisition (CS1 and CS2).",
        phaseSummary: "Compound Acquisition",
        mechanisms: ["Salience"],
        teaches: "How two cues learn together and how cue strength balance affects compound learning.",
        builderNext: "Adjust salience per cue and compare asymmetry between CS1 and CS2.",
        nextPhenomenon: "Blocking",
        href: "/ui/presets/compound_acquisition.html",
      }),
      preset({
        name: "Differential Acquisition",
        description: "Phase: Differential Acquisition (CS+ vs CS-).",
        phaseSummary: "Differential Acquisition",
        mechanisms: ["Similarity"],
        teaches: "How the system separates reinforced and nonreinforced cues.",
        builderNext: "Enable similarity and test how CS- responds as similarity to CS+ increases.",
        nextPhenomenon: "Overshadowing",
        href: "/ui/presets/differential_acquisition.html",
      }),
    ]
  },
  {
    title: "Salience and Cue Competition",
    note: "Use these presets to explore cue weighting and competition dynamics.",
    items: [
      preset({
        name: "Overexpectation",
        description: "Phases: Acquisition (A+, B+) -> Compound Acquisition (AB+).",
        phaseSummary: "Acquisition -> Compound Acquisition",
        mechanisms: ["Salience"],
        teaches: "How combining already predictive cues can induce expectation mismatch.",
        builderNext: "Adjust acquisition/compound trial counts to see overexpectation sensitivity.",
        nextPhenomenon: "Conditioned Inhibition",
        href: "/ui/presets/overexpectation.html",
      }),
      preset({
        name: "Relative Cue Dominance",
        description: "Phase: Compound Acquisition (A+B+) with unequal cue salience.",
        phaseSummary: "Compound Acquisition",
        mechanisms: ["Salience"],
        teaches: "How a higher-salience cue dominates prediction in a reinforced compound.",
        builderNext: "Sweep salience ratio across cues and compare final cue strengths.",
        nextPhenomenon: "Salience-Driven Competition",
        href: "/ui/presets/relative_cue_dominance.html",
      }),
      preset({
        name: "Salience-Driven Competition",
        description: "Phase: Compound Acquisition (A+B+) with strong salience asymmetry.",
        phaseSummary: "Compound Acquisition",
        mechanisms: ["Salience"],
        teaches: "How a strongly weighted cue suppresses learning in a weaker competing cue.",
        builderNext: "Increase/decrease weaker-cue salience and inspect competition recovery.",
        nextPhenomenon: "Asymmetric Extinction",
        href: "/ui/presets/salience_competition.html",
      }),
      preset({
        name: "Asymmetric Extinction",
        description: "Phases: Compound Acquisition -> Nonreinforcement.",
        phaseSummary: "Compound Acquisition -> Nonreinforcement",
        mechanisms: ["Salience"],
        teaches: "How a higher-salience cue can extinguish more slowly after compound training.",
        builderNext: "Change extinction length and salience asymmetry to compare persistence.",
        nextPhenomenon: "Salience-Dependent Acquisition Rate",
        href: "/ui/presets/asymmetric_extinction.html",
      }),
      preset({
        name: "Salience-Dependent Acquisition Rate",
        description: "Phase: Acquisition with adjustable CS salience.",
        phaseSummary: "Acquisition",
        mechanisms: ["Salience"],
        teaches: "How salience scales the speed of associative acquisition.",
        builderNext: "Compare low vs high salience runs with matched alpha/trials.",
        nextPhenomenon: "Salience Bias in Differential Conditioning",
        href: "/ui/presets/salience_acquisition_rate.html",
      }),
      preset({
        name: "Salience Bias in Differential Conditioning",
        description: "Phase: Differential Acquisition with independent CS+ and CS- salience.",
        phaseSummary: "Differential Acquisition",
        mechanisms: ["Salience"],
        teaches: "How CS+ salience amplifies discrimination against CS- in differential conditioning.",
        builderNext: "Shift CS- salience upward and inspect reduced discrimination.",
        href: "/ui/presets/salience_bias_differential.html",
      }),
      preset({
        name: "Conditioned Inhibition",
        description: "Phases: Acquisition -> Compound Nonreinforcement -> Probe.",
        phaseSummary: "Acquisition -> Compound Nonreinforcement -> Probe",
        mechanisms: ["Salience"],
        teaches: "How inhibitory cue structure suppresses responding in compound presentations.",
        builderNext: "Modify inhibition/probe proportions and compare suppression strength.",
        href: "/ui/presets/conditioned_inhibition.html",
      }),
      preset({
        name: "ABA Renewal",
        description: "Phases: Acquisition (A) -> Context Shift (B) -> Nonreinforcement -> Context Shift (A) -> Probe.",
        phaseSummary: "Acquisition -> Context Shift -> Nonreinforcement -> Context Shift -> Probe",
        mechanisms: ["Context"],
        teaches: "How returning to the original context can recover responding after extinction.",
        builderNext: "Toggle context inference and compare inferred vs explicit context behavior.",
        href: "/ui/presets/aba_renewal.html",
      }),
      preset({
        name: "ABC Renewal",
        description: "Phases: Acquisition (A) -> Context Shift (B) -> Nonreinforcement -> Context Shift (C) -> Probe.",
        phaseSummary: "Acquisition -> Context Shift -> Nonreinforcement -> Context Shift -> Probe",
        mechanisms: ["Context"],
        teaches: "How a novel probe context can partially recover responding after extinction elsewhere.",
        builderNext: "Swap probe context and compare ABC against ABA/AAB response recovery.",
        href: "/ui/presets/abc_renewal.html",
      }),
      preset({
        name: "AAB Renewal",
        description: "Phases: Acquisition (A) -> Nonreinforcement (A) -> Context Shift (B) -> Probe.",
        phaseSummary: "Acquisition -> Nonreinforcement -> Context Shift -> Probe",
        mechanisms: ["Context"],
        teaches: "How shifting probe context without extinction-context mismatch changes recovery pattern.",
        builderNext: "Test AAB vs ABA with identical trial counts to isolate context effects.",
        href: "/ui/presets/aab_renewal.html",
      }),
      preset({
        name: "Rapid Reacquisition",
        description: "Phases: Acquisition (A) -> Context Shift (B) -> Nonreinforcement -> Context Shift (A) -> Acquisition.",
        phaseSummary: "Acquisition -> Context Shift -> Nonreinforcement -> Context Shift -> Acquisition",
        mechanisms: ["Context"],
        teaches: "How relearning can occur rapidly when returning to a prior learning context.",
        builderNext: "Modify extinction depth and test how it changes reacquisition speed.",
        href: "/ui/presets/rapid_reacquisition.html",
      }),
      preset({
        name: "Occasion Setting",
        description: "Phases: Acquisition (S+X) -> Nonreinforcement (X) -> Probe.",
        phaseSummary: "Acquisition -> Nonreinforcement -> Probe",
        mechanisms: ["Context"],
        teaches: "How one cue can modulate meaning of another cue across phase structure.",
        builderNext: "Adjust salience on setting vs target cue and inspect probe separation.",
        href: "/ui/presets/occasion_setting.html",
      }),
      preset({
        name: "Blocking",
        description: "Phases: Acquisition (A+) -> Compound Acquisition (AX+).",
        phaseSummary: "Acquisition -> Compound Acquisition",
        mechanisms: ["Salience"],
        teaches: "How prior learning on one cue can limit learning to a new added cue.",
        builderNext: "Change initial acquisition length to see blocking strength differences.",
        nextPhenomenon: "Overexpectation",
        href: "/ui/presets/blocking.html",
      }),
      preset({
        name: "Conditioned Inhibition",
        description: "Phases: Acquisition -> Compound Nonreinforcement -> Probe.",
        phaseSummary: "Acquisition -> Compound Nonreinforcement -> Probe",
        mechanisms: ["Salience"],
        teaches: "How inhibitory cue structure suppresses responding in compound presentations.",
        builderNext: "Modify inhibition/probe proportions and compare suppression strength.",
        nextPhenomenon: "ABA Renewal",
        href: "/ui/presets/conditioned_inhibition.html",
      }),
    ]
  },
  {
    title: "Attention and Selectivity",
    note: "Learn how cue-specific learning-rate scaling shapes what is learned fastest.",
    items: [
      preset({
        name: "Latent Inhibition",
        description: "Phases: Nonreinforcement (preexposure) -> Acquisition.",
        phaseSummary: "Nonreinforcement -> Acquisition",
        mechanisms: ["Attention"],
        teaches: "Preexposure can reduce attention to a familiar cue before reinforcement begins.",
        builderNext: "Increase preexposure trials and compare slower acquisition in phase two.",
        nextPhenomenon: "Learned Irrelevance",
        href: "/ui/presets/attention_latent_inhibition.html",
      }),
      preset({
        name: "Learned Irrelevance",
        description: "Phase: Differential Acquisition with weak cue predictiveness.",
        phaseSummary: "Differential Acquisition",
        mechanisms: ["Attention"],
        teaches: "When cues are weakly predictive, attention can decline and reduce later learning impact.",
        builderNext: "Shift CS+/CS- attention levels and compare discrimination quality.",
        nextPhenomenon: "Hall-Pearce Negative Transfer",
        href: "/ui/presets/attention_learned_irrelevance.html",
      }),
      preset({
        name: "Hall-Pearce Negative Transfer",
        description: "Phases: Weak Acquisition -> Strong Acquisition.",
        phaseSummary: "Acquisition (weak) -> Acquisition (strong)",
        mechanisms: ["Attention"],
        teaches: "Early weak training can reduce attention and slow later strong learning.",
        builderNext: "Adjust weak-phase length and compare transfer cost in phase two.",
        nextPhenomenon: "Mackintosh Predictiveness Effect",
        href: "/ui/presets/attention_hall_pearce_negative_transfer.html",
      }),
      preset({
        name: "Mackintosh Predictiveness Effect",
        description: "Phase: Differential Acquisition (predictive vs nonpredictive cues).",
        phaseSummary: "Differential Acquisition",
        mechanisms: ["Attention"],
        teaches: "Attention increases for cues that are more predictive of outcomes.",
        builderNext: "Raise CS+ attention and compare separation from CS- trajectories.",
        nextPhenomenon: "Pearce-Hall Uncertainty Learning",
        href: "/ui/presets/attention_mackintosh_predictiveness.html",
      }),
      preset({
        name: "Pearce-Hall Uncertainty Learning",
        description: "Phase: Acquisition under high uncertainty.",
        phaseSummary: "Acquisition",
        mechanisms: ["Attention"],
        teaches: "Attention can increase when prediction error remains high.",
        builderNext: "Hold alpha fixed and compare attention-weighted learning under uncertainty.",
        nextPhenomenon: "Rapid Reacquisition",
        href: "/ui/presets/attention_pearce_hall_uncertainty.html",
      }),
      preset({
        name: "Rapid Reacquisition (Attention)",
        description: "Phases: Acquisition -> Nonreinforcement -> Acquisition.",
        phaseSummary: "Acquisition -> Nonreinforcement -> Acquisition",
        mechanisms: ["Attention"],
        teaches: "Attention can remain elevated after extinction, accelerating relearning.",
        builderNext: "Increase extinction depth and compare reacquisition speed.",
        nextPhenomenon: "Associability Shifts",
        href: "/ui/presets/attention_rapid_reacquisition.html",
      }),
      preset({
        name: "Associability Shifts",
        description: "Phases: Acquisition -> Compound Acquisition.",
        phaseSummary: "Acquisition -> Compound Acquisition",
        mechanisms: ["Attention"],
        teaches: "Attention redistributes across cues when moving from single-cue to compound learning.",
        builderNext: "Vary cue attention asymmetry in the compound phase and compare allocation.",
        href: "/ui/presets/attention_associability_shifts.html",
      }),
    ]
  },
  {
    title: "Similarity and Generalization",
    note: "Probe how representational overlap transfers learning between cues.",
    items: [
      preset({
        name: "Differential Acquisition",
        description: "Phase: Differential Acquisition (CS+ vs CS-).",
        phaseSummary: "Differential Acquisition",
        mechanisms: ["Similarity"],
        teaches: "How cue separation and generalization depend on similarity structure.",
        builderNext: "Enable similarity matrix in builder and sweep off-diagonal values.",
        nextPhenomenon: "Occasion Setting",
        href: "/ui/presets/differential_acquisition.html",
      }),
    ]
  },
  {
    title: "Context and Retrieval",
    note: "Study context-dependent expression, recovery, and reinstatement-like effects.",
    items: [
      preset({
        name: "ABA Renewal",
        description: "Phases: Acquisition (A) -> Context Shift (B) -> Nonreinforcement -> Context Shift (A) -> Probe.",
        phaseSummary: "Acquisition -> Context Shift -> Nonreinforcement -> Context Shift -> Probe",
        mechanisms: ["Context"],
        teaches: "How returning to the original context can recover responding after extinction.",
        builderNext: "Toggle context inference and compare inferred vs explicit context behavior.",
        nextPhenomenon: "ABC Renewal",
        href: "/ui/presets/aba_renewal.html",
      }),
      preset({
        name: "ABC Renewal",
        description: "Phases: Acquisition (A) -> Context Shift (B) -> Nonreinforcement -> Context Shift (C) -> Probe.",
        phaseSummary: "Acquisition -> Context Shift -> Nonreinforcement -> Context Shift -> Probe",
        mechanisms: ["Context"],
        teaches: "How a novel probe context can partially recover responding after extinction elsewhere.",
        builderNext: "Swap probe context and compare ABC against ABA/AAB response recovery.",
        nextPhenomenon: "Rapid Reacquisition",
        href: "/ui/presets/abc_renewal.html",
      }),
      preset({
        name: "AAB Renewal",
        description: "Phases: Acquisition (A) -> Nonreinforcement (A) -> Context Shift (B) -> Probe.",
        phaseSummary: "Acquisition -> Nonreinforcement -> Context Shift -> Probe",
        mechanisms: ["Context"],
        teaches: "How shifting probe context without extinction-context mismatch changes recovery pattern.",
        builderNext: "Test AAB vs ABA with identical trial counts to isolate context effects.",
        nextPhenomenon: "ABA Renewal",
        href: "/ui/presets/aab_renewal.html",
      }),
      preset({
        name: "Rapid Reacquisition",
        description: "Phases: Acquisition (A) -> Context Shift (B) -> Nonreinforcement -> Context Shift (A) -> Acquisition.",
        phaseSummary: "Acquisition -> Context Shift -> Nonreinforcement -> Context Shift -> Acquisition",
        mechanisms: ["Context"],
        teaches: "How relearning can occur rapidly when returning to a prior learning context.",
        builderNext: "Modify extinction depth and test how it changes reacquisition speed.",
        nextPhenomenon: "Occasion Setting",
        href: "/ui/presets/rapid_reacquisition.html",
      }),
      preset({
        name: "Occasion Setting",
        description: "Phases: Acquisition (S+X) -> Nonreinforcement (X) -> Probe.",
        phaseSummary: "Acquisition -> Nonreinforcement -> Probe",
        mechanisms: ["Context"],
        teaches: "How one cue can modulate meaning of another cue across phase structure.",
        builderNext: "Adjust salience on setting vs target cue and inspect probe separation.",
        nextPhenomenon: "ABA Renewal",
        href: "/ui/presets/occasion_setting.html",
      }),
    ],
  },
  {
    title: "Operant Decision Learning",
    note: "Action-value learning under reinforcement schedules and concurrent choice.",
    items: [
      preset({
        name: "Operant Conditioning",
        description: "Phase: Operant Acquisition (operant schedule).",
        phaseSummary: "Operant Acquisition",
        teaches: "How action values rise under reinforcement schedules.",
        builderNext: "Modify schedule parameters and compare action value trajectories.",
        nextPhenomenon: "Matching Law",
        href: "/ui/presets/operant_conditioning.html",
      }),
      preset({
        name: "Matching Law",
        description: "Protocol: Concurrent schedules (left/right) with operant choice.",
        phaseSummary: "Matching Law",
        teaches: "How action selection matches relative reinforcement rates across options.",
        builderNext: "Change left/right schedule ratios and inspect choice allocation shifts.",
        nextPhenomenon: "Shaping",
        href: "/ui/presets/matching_law.html",
      }),
      preset({
        name: "Shaping",
        description: "Protocol: FR-1 shaping stage -> harder FR stage.",
        phaseSummary: "Operant Acquisition -> Operant Acquisition",
        teaches: "How behavior is maintained as reinforcement schedules become more demanding.",
        builderNext: "Change FR values across stages to compare reward-density drops.",
        nextPhenomenon: "Resurgence",
        href: "/ui/presets/shaping.html",
      }),
      preset({
        name: "Resurgence",
        description: "Protocol: Reinforcement -> suppression/extinction -> recovery block.",
        phaseSummary: "Operant Acquisition -> Operant Acquisition -> Operant Acquisition",
        teaches: "How response strength returns after suppression when reinforcement is restored.",
        builderNext: "Adjust suppression duration and compare recovery magnitude.",
        nextPhenomenon: "Superextinction",
        href: "/ui/presets/resurgence.html",
      }),
      preset({
        name: "Superextinction",
        description: "Protocol: Reinforcement -> explicit punishment block.",
        phaseSummary: "Operant Acquisition -> Operant Acquisition",
        teaches: "How negative outcomes drive rapid suppression beyond omission alone.",
        builderNext: "Sweep punishment magnitude and compare suppression rates.",
        nextPhenomenon: "Spontaneous Recovery",
        href: "/ui/presets/superextinction.html",
      }),
      preset({
        name: "Spontaneous Recovery",
        description: "Protocol: A reinforced -> B extinction -> A probe.",
        phaseSummary: "Acquisition (A) -> Extinction (B) -> Probe (A)",
        teaches: "How context return can recover responding after extinction.",
        builderNext: "Compare context A/B assignments and probe schedule effects.",
        nextPhenomenon: "Build Your Own",
        href: "/ui/presets/spontaneous_recovery.html",
      }),
    ],
  }
];
