"""UI-facing typed contracts."""

from ui.contracts.builder_draft import (
    BuilderDraftValidationError,
    BuilderExperimentDraft,
    BuilderPhaseDraft,
    BuilderRuntimeDraft,
)
from ui.contracts.operator_registry import (
    OPERATOR_REGISTRY,
    OPERATOR_REGISTRY_VERSION,
    REQUIRED_OPERATOR_FAMILIES,
    REQUIRED_OPERATORS,
    OperatorRegistryValidationError,
    get_operator,
    get_operator_registry,
    list_operator_ids,
    validate_operator_registry,
)
from ui.contracts.operator_graph_backlinks import (
    OperatorGraphBacklinkError,
    list_operator_graph_backlinks,
    resolve_operator_graph_backlinks,
    validate_operator_graph_backlink_integrity_from_payloads,
    validate_operator_graph_backlink_integrity,
)
from ui.contracts.dependent_variable_registry import (
    DEPENDENT_VARIABLE_REGISTRY,
    DEPENDENT_VARIABLE_REGISTRY_VERSION,
    REQUIRED_DEPENDENT_VARIABLE_CATEGORIES,
    REQUIRED_DEPENDENT_VARIABLES,
    DependentVariableRegistryValidationError,
    get_dependent_variable,
    get_dependent_variable_registry,
    list_dependent_variable_ids,
    validate_dependent_variable_ids,
    validate_dependent_variable_registry,
    validate_preset_results_contract,
)
from ui.contracts.dependent_variable_resolver import (
    DependentVariableResolverError,
    resolve_dependent_variable,
    resolve_dependent_variable_from_registry_payload,
    resolve_dependent_variables_for_surface,
    resolve_report_variable,
    resolve_results_variable,
)
from ui.contracts.preset_registry import (
    PRESET_REGISTRY,
    PRESET_REGISTRY_VERSION,
    PresetRegistryValidationError,
    get_preset,
    get_preset_registry,
    list_preset_ids,
    validate_acquisition_preset_invariants,
    validate_preset_registry,
)
from ui.contracts.registry_integrity import (
    UIRegistryIntegrityError,
    load_ui_registries,
    validate_ui_registry_integrity,
)
from ui.contracts.preset_detail_contract import (
    PresetDetailContractError,
    build_preset_detail_contract,
)
from ui.contracts.preset_materialization import (
    PresetMaterializationError,
    materialize_preset_payload,
    stable_materialized_payload_hash,
    stable_materialized_payload_json,
    validate_materialized_payload_boundary,
)
from ui.contracts.preset_run_flow import (
    PresetRunFlowContractError,
    build_preset_run_flow_contract,
    resolve_preset_results_view,
    resolve_results_contract_from_preset,
    validate_preset_results_priority,
)
from ui.contracts.preset_hardening import (
    PresetHardeningError,
    build_trial_hover_overlay,
    decode_results_return_state,
    encode_results_return_state,
    validate_preset_form_edits,
)
from ui.contracts.trial_hover_explainability import (
    TrialHoverExplainabilityError,
    build_trial_hover_explainability_panel,
)
from ui.contracts.trialstate_inspector import (
    ALLOWED_INSPECTOR_MODES,
    TrialStateInspectorError,
    build_trialstate_inspector,
)
from ui.contracts.trialstate_registry import (
    REQUIRED_TRIALSTATE_FIELDS,
    REQUIRED_TRIALSTATE_FIELD_GROUPS,
    TRIALSTATE_FIELD_REGISTRY,
    TRIALSTATE_FIELD_REGISTRY_VERSION,
    TrialStateRegistryValidationError,
    get_trialstate_field,
    get_trialstate_field_registry,
    list_trialstate_field_ids,
    validate_trialstate_field_registry,
)
from ui.contracts.translator import draft_to_payload

__all__ = [
    "BuilderDraftValidationError",
    "BuilderExperimentDraft",
    "BuilderPhaseDraft",
    "BuilderRuntimeDraft",
    "draft_to_payload",
    "OperatorRegistryValidationError",
    "OPERATOR_REGISTRY_VERSION",
    "OPERATOR_REGISTRY",
    "REQUIRED_OPERATOR_FAMILIES",
    "REQUIRED_OPERATORS",
    "validate_operator_registry",
    "get_operator_registry",
    "list_operator_ids",
    "get_operator",
    "OperatorGraphBacklinkError",
    "resolve_operator_graph_backlinks",
    "list_operator_graph_backlinks",
    "validate_operator_graph_backlink_integrity_from_payloads",
    "validate_operator_graph_backlink_integrity",
    "DependentVariableRegistryValidationError",
    "DEPENDENT_VARIABLE_REGISTRY_VERSION",
    "DEPENDENT_VARIABLE_REGISTRY",
    "REQUIRED_DEPENDENT_VARIABLE_CATEGORIES",
    "REQUIRED_DEPENDENT_VARIABLES",
    "validate_dependent_variable_registry",
    "get_dependent_variable_registry",
    "list_dependent_variable_ids",
    "get_dependent_variable",
    "validate_dependent_variable_ids",
    "validate_preset_results_contract",
    "DependentVariableResolverError",
    "resolve_dependent_variable",
    "resolve_dependent_variable_from_registry_payload",
    "resolve_dependent_variables_for_surface",
    "resolve_results_variable",
    "resolve_report_variable",
    "PresetRegistryValidationError",
    "PRESET_REGISTRY_VERSION",
    "PRESET_REGISTRY",
    "validate_preset_registry",
    "validate_acquisition_preset_invariants",
    "get_preset_registry",
    "list_preset_ids",
    "get_preset",
    "UIRegistryIntegrityError",
    "load_ui_registries",
    "validate_ui_registry_integrity",
    "PresetDetailContractError",
    "build_preset_detail_contract",
    "PresetMaterializationError",
    "materialize_preset_payload",
    "stable_materialized_payload_json",
    "stable_materialized_payload_hash",
    "validate_materialized_payload_boundary",
    "PresetRunFlowContractError",
    "build_preset_run_flow_contract",
    "resolve_preset_results_view",
    "resolve_results_contract_from_preset",
    "validate_preset_results_priority",
    "PresetHardeningError",
    "build_trial_hover_overlay",
    "encode_results_return_state",
    "decode_results_return_state",
    "validate_preset_form_edits",
    "TrialHoverExplainabilityError",
    "build_trial_hover_explainability_panel",
    "TrialStateInspectorError",
    "ALLOWED_INSPECTOR_MODES",
    "build_trialstate_inspector",
    "TrialStateRegistryValidationError",
    "TRIALSTATE_FIELD_REGISTRY_VERSION",
    "TRIALSTATE_FIELD_REGISTRY",
    "REQUIRED_TRIALSTATE_FIELD_GROUPS",
    "REQUIRED_TRIALSTATE_FIELDS",
    "validate_trialstate_field_registry",
    "get_trialstate_field_registry",
    "list_trialstate_field_ids",
    "get_trialstate_field",
]
